lib/mafia_web/router.ex
defmodule MafiaWeb.Router do
  use MafiaWeb, :router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MafiaWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authorizedUser do
    plug(MafiaWeb.Plug.EnsureUserLoggedIn)
  end

  pipeline :superAdmin do
    plug(MafiaWeb.Plug.EnsureSuperAdmin)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MafiaWeb do
    pipe_through :browser
    live "/signin", SignInLive, :index
    get("/login/:user_id/:role/:mobile", SessionController, :login)
    get("/logout", SessionController, :logout)

  end

  scope "/", MafiaWeb do
    pipe_through [:browser, :authorizedUser]
    live "/", PageLive, :index
  end


  scope "/game/", MafiaWeb do
    pipe_through [:browser, :authorizedUser]
    live "/play/", UserContestLive.Performance, :index
    live "/leaderboard/", LeaderboardLive.Total, :index
  end

  scope "/super-admin/", MafiaWeb do
    pipe_through [:browser, :authorizedUser, :superAdmin]

    live_dashboard "/dashboard", metrics: Telemetry
    live "/session/contest/:session_id", ContestLive.Performance, :index

    live "/user", UserLive.Index, :index
    live "/user/new", UserLive.Index, :new
    live "/user/:id/edit", UserLive.Index, :edit
    live "/user/:id", UserLive.Show, :show
    live "/user/:id/show/edit", UserLive.Show, :edit

    live "/session", SessionLive.Index, :index
    live "/session/new", SessionLive.Index, :new
    live "/session/:id/edit", SessionLive.Index, :edit
    live "/session/:id", SessionLive.Show, :show
    live "/session/:id/show/edit", SessionLive.Show, :edit


    live "/question/list/:session_id", QuestionLive.Index, :index
    live "/question/new", QuestionLive.Index, :new
    live "/question/:id/edit", QuestionLive.Index, :edit
#    live "/question/:id", QuestionLive.Show, :show
    live "/question/:id/show/edit", QuestionLive.Show, :edit


    live "/answer/list/:session_id/:question_id", AnswerLive.Index, :index
    live "/answer/new", AnswerLive.Index, :new
    live "/answer/:id/edit", AnswerLive.Index, :edit
#    live "/answer/:id", AnswerLive.Show, :show
    live "/answer/:id/show/edit", AnswerLive.Show, :edit

    live "/user_vote", UserVoteLive.Index, :index
    live "/user_vote/new", UserVoteLive.Index, :new
    live "/user_vote/:id/edit", UserVoteLive.Index, :edit

    live "/user_vote/:id", UserVoteLive.Show, :show
    live "/user_vote/:id/show/edit", UserVoteLive.Show, :edit


    live "/user_total_point", UserTotalPointLive.Index, :index
    live "/user_total_point/new", UserTotalPointLive.Index, :new
    live "/user_total_point/:id/edit", UserTotalPointLive.Index, :edit

    live "/user_total_point/:id", UserTotalPointLive.Show, :show
    live "/user_total_point/:id/show/edit", UserTotalPointLive.Show, :edit




  end

  # Other scopes may use custom stacks.
  # scope "/api", MafiaWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
#    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MafiaWeb.Telemetry
    end
  end
end

lib/mafia_web/live/answer_live/form_component.ex
defmodule MafiaWeb.AnswerLive.FormComponent do
  use MafiaWeb, :live_component

  alias Mafia.Game

  @impl true
  def update(%{answer: answer} = assigns, socket) do
    changeset = Game.change_answer(answer)

    {:ok,
     socket
     |> assign(assigns)
     |> allow_upload(:uploaded_image, accept: ~w(.png .jpg .jpeg), max_entries: 1)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"answer" => answer_params}, socket) do
    changeset =
      socket.assigns.answer
      |> Game.change_answer(answer_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"answer" => answer_params}, socket) do
    uploaded_files =
      consume_uploaded_entries(
        socket,
        :uploaded_image,
        fn %{path: path}, _entry ->
          dest = Path.join("priv/static/uploads", Path.basename(path))
          File.cp!(path, dest)
          Routes.static_path(socket, "/uploads/#{Path.basename(dest)}")
        end
      )
    if uploaded_files |> List.first()  do
      save_answer(
        socket,
        socket.assigns.action,
        Map.put(
          answer_params,
          "image_path",
          uploaded_files
          |> List.first()
        )
      )
    else
      save_answer(socket, socket.assigns.action, answer_params)
    end
  end

  defp save_answer(socket, :edit, answer_params) do
    case Game.update_answer(socket.assigns.answer, answer_params) do
      {:ok, _answer} ->
        {:noreply,
         socket
         |> put_flash(:info, "گزینه با موفقیت ویرایش شد")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_answer(socket, :new, answer_params) do
#    IO.inspect(socket.assigns.question_id)
    answer_params = Map.put(answer_params, "question_id" , socket.assigns.question_id)
    answer_params = Map.put(answer_params, "count" , 0)
    case Game.create_answer(answer_params) do
      {:ok, _answer} ->
        {:noreply,
         socket
         |> put_flash(:info, "گزینه با موفقیت اضافه شد")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/mafia_web/live/answer_live/index.ex
defmodule MafiaWeb.AnswerLive.Index do
  use MafiaWeb, :live_view

  alias Mafia.Game
  alias Mafia.Game.Answer

  @impl true
  def mount(%{"question_id" => question_id, "session_id" => session_id}, _session, socket) do
    {
      :ok,
      socket
      |> assign(:answer_collection, list_answer(question_id))
      |> assign(:question_id, question_id)
      |> assign(:session_id, session_id)
    }
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "ویرایش گزینه")
    |> assign(:answer, Game.get_answer!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "افزودن گزینه جدید")
    |> assign(:answer, %Answer{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "لیست گزینه ها")
    |> assign(:answer, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    answer = Game.get_answer!(id)
    {:ok, _} = Game.delete_answer(answer, %{is_deleted: true})
    question_id = socket.assigns.question_id
    {:noreply, assign(socket, :answer_collection, list_answer(question_id))}
  end

  defp list_answer(question_id) do
    Game.list_answer(question_id)
  end
end

lib/mafia_web/live/answer_live/show.ex
defmodule MafiaWeb.AnswerLive.Show do
  use MafiaWeb, :live_view

  alias Mafia.Game

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:answer, Game.get_answer!(id))}
  end

  defp page_title(:show), do: "Show Answer"
  defp page_title(:edit), do: "Edit Answer"
end

lib/mafia_web/live/leaderboard_total_live/total.ex
defmodule MafiaWeb.LeaderboardLive.Total do
  use MafiaWeb, :live_view
  require Logger
  alias Mafia.Presence

  @presence "mafia:presence"
  @impl true
  def mount(_params, _session, socket) do
    user_ranks = case Mafia.Redis.get_by_key("#{Application.get_env(:mafia, :product_name)}_total_leaderboard_ranks") do
      {:ok, nil} ->
        ranks = get_users_ranks()
        {:ok, string_ranks} = Jason.encode(ranks)
        Mafia.Redis.set_by_key("#{Application.get_env(:mafia, :product_name)}_total_leaderboard_ranks", string_ranks)
        ranks
      {:ok, value} ->
        {:ok, result} = Jason.decode(value, [{:keys, :atoms}])
        result
      _ ->
        ranks = get_users_ranks()
        {:ok, string_ranks} = Jason.encode(ranks)
        Mafia.Redis.set_by_key("#{Application.get_env(:mafia, :product_name)}_total_leaderboard_ranks", string_ranks)
        ranks
    end

    [total_point, rank] = case  result = Mafia.Accounts.get_user_latest_total_point!(_session["user"].id) do
      nil ->
        [0,0]
      _ ->
        [result.total_point, result.rank]
      end

    sessions_list = case Mafia.Redis.get_by_key("#{Application.get_env(:mafia, :product_name)}_sessions_list") do
      {:ok, nil } ->
          get_sessions_list_from_database()
      {:ok, value} ->
          { :ok, decoded_sessions } = Jason.decode(value, [{:keys, :atoms}])
          decoded_sessions
        _ ->
          get_sessions_list_from_database()
    end

    {
      :ok,
      socket
      |> assign(:user_ranks, user_ranks)
      |> assign(:user_leaderboard_data, %{total_point: total_point, rank: rank})
      |> assign(:current_user, _session["user"])
      |> assign(:sessions_list, sessions_list)
      |> assign(:sessions_leaderboard_data, [])
      |> assign(:current_user_session_total_point, 0)
      |> assign(:current_user_session_rank, 0)
      |> assign(:expanded, false)
      |> assign(:page_title, "لیدربرد مسابقه")
    }
  end


  defp calculate_rank!(user_list) do
    user_list
    |> Enum.group_by(fn x -> x.total_point end)
    |> Enum.sort_by(&(&1), :desc)
    |> Enum.with_index
    |> Enum.into([], fn {{point, users}, rank} -> Enum.map(users, fn user -> Map.put(user, :rank, rank + 1) end) end)
    |> List.flatten()
  end

  defp get_users_ranks() do
    total_points = Mafia.Accounts.get_users_total_points!(1)
    calculate_rank!(total_points)
  end

  @impl true
  def handle_event("get_specific_session_data", %{"session_id" => session_id}, socket) do
    case session_id do
      "nothing" ->
        {
          :noreply,
          socket
        }
      _ ->
        session_data = case is_integer(session_id) do
          false ->
            get_specific_session_data(Mafia.Utility.parsInt(session_id))
          true ->
            get_specific_session_data(session_id)
        end
        [current_user_session_rank, current_user_total_point] = get_user_session_data!(session_id, socket.assigns.current_user.id)
        {
          :noreply,
          socket
          |> assign(:sessions_leaderboard_data, session_data)
          |> assign(:current_user_session_total_point, current_user_total_point)
          |> assign(:current_user_session_rank, current_user_session_rank)
        }
    end
  end


  defp get_sessions_list_from_database() do
    sessions = Mafia.Game.list_session_published()
    { :ok, encoded_sessions } = Jason.encode(Mafia.Game.Session.session_cast(sessions))
    Mafia.Redis.set_by_key("#{Application.get_env(:mafia, :product_name)}_sessions_list", encoded_sessions)
    sessions
  end

  defp get_specific_session_data(session_id) do
    case is_integer(session_id) do
      false ->
        Mafia.Accounts.list_user_session_total_point_by_session_id_sorted_by_rank(Mafia.Utility.parsInt(session_id))
      true ->
        Mafia.Accounts.list_user_session_total_point_by_session_id_sorted_by_rank(session_id)
    end
  end

  defp get_user_session_data!(session_id, user_id) do
    case Mafia.Accounts.get_user_session_total_point_by_session_id!(session_id, user_id) do
      value = %Mafia.Accounts.UserSessionTotalPoint{} ->
        [value.rank, value.total_point]
      nil ->
        [0, 0]

    end
  end

  @impl true
  def handle_event("toggle", _value, socket) do
    {:noreply, assign(socket, :expanded, !socket.assigns.expanded)}
  end
end

lib/mafia_web/live/live_helpers.ex
defmodule MafiaWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `MafiaWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, MafiaWeb.UserLive.FormComponent,
        id: @user.id || :new,
        action: @live_action,
        user: @user,
        return_to: Routes.user_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, MafiaWeb.ModalComponent, modal_opts)
  end
end

lib/mafia_web/live/modal_component.ex
defmodule MafiaWeb.ModalComponent do
  use MafiaWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/mafia_web/live/page_live.ex
defmodule MafiaWeb.PageLive do
  use MafiaWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    if connected?(socket) do
      Mafia.Game.subscribe()
    end
    is_playing = case (Mafia.Redis.get_by_key("#{Application.get_env(:mafia, :product_name)}_is_playing")) do
      {:ok, nil} ->
        false
      {:ok, value} ->
        if value == "1" do
          true
        else
          false
        end
      _ ->
        false
    end
    {:ok, assign(socket, query: "", results: %{})
      |> assign(:current_user, _session["user"])
      |> assign(:is_playing, is_playing)
      |> assign(:expanded, false)
    }
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not MafiaWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end

  @impl true
  def handle_info({:game_started, message}, socket) do
    {
      :noreply,
      socket
      |> assign(:is_playing, true)
    }
  end

  @impl true
  def handle_info({:game_ended, message}, socket) do
    {
      :noreply,
      socket
      |> assign(:is_playing, false)
    }
  end

  @impl true
  def handle_info({:leaderboard_calculating, message}, socket) do
    {
      :noreply,
      socket
    }
  end

  @impl true
  def handle_info({:leaderboard_is_ready, message}, socket) do
#    user_data = Mafia.Redis.get_by_key!("#{Application.get_env(:mafia, :product_name)}_statistics-#{socket.assigns.question.session_id}-#{socket.assigns.current_user.id}")
    {
      :noreply,
      socket
    }
  end

  @impl true
  def handle_info({:leaderboard_process_done, message}, socket) do
    {
      :noreply,
      socket
    }
  end

  @impl true
  def handle_info({:countdown_updated, message}, socket) do
    {
      :noreply,
      socket
    }
  end

  @impl true
  def handle_info({:online_user_updated, message}, socket) do
    {:ok, online_users} = Mafia.Redis.get_by_key("#{Application.get_env(:mafia, :product_name)}_online_users")
    {
      :noreply,
      socket
    }
  end


  @impl true
  def handle_info({:question_timeout, message}, socket) do
    {:noreply, socket}
  end

  @impl true
  def handle_info({:new_question_showed, message}, socket) do
    {:noreply, socket}
  end

  @impl true
  def handle_info({:leaderboard_status_changed, message}, socket) do
    {
      :noreply,
      socket
    }
  end

  @impl true
  def handle_info({:refresh_game_page, message}, socket) do
    {
      :noreply,
      socket
    }
  end

  @impl true
  def handle_event("toggle", _value, socket) do
    {:noreply, assign(socket, :expanded, !socket.assigns.expanded)}
  end
end

lib/mafia_web/live/question_live/show.ex
defmodule MafiaWeb.QuestionLive.Show do
  use MafiaWeb, :live_view

  alias Mafia.Game

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:question, Game.get_question!(id))}
  end

  defp page_title(:show), do: "Show Question"
  defp page_title(:edit), do: "Edit Question"
end

lib/mafia_web/live/session_live/form_component.html.leex
<div style="direction: rtl;">
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "session-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <%= #label f, :title %>
<label for="session_<%= :title %>">عنوان مسابقه</label>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= #label f, :description %>
<label for="session_<%= :description %>">توضیحات مسابقه</label>
  <%= text_input f, :description %>
  <%= error_tag f, :description %>

  <%= #label f, :image_path %>
<label for="session_<%= :image_path %>">عکس</label>
  <%= text_input f, :image_path %>
  <%= error_tag f, :image_path %>

  <%= #label f, :video_path %>
<!-- <label for="answer_<%= :is_correct %>">گزینه صحیح</label> -->
  <%= #text_input f, :video_path %>
  <%= #error_tag f, :video_path %>

  <%= #label f, :is_published %>
<label for="session_<%= :is_published %>">انتشار یافته</label>
  <%= checkbox f, :is_published %>
  <%= error_tag f, :is_published %>

  <%= #label f, :is_closed %>
<label for="session_<%= :is_closed %>">بسته شده</label>
  <%= checkbox f, :is_closed %>
  <%= error_tag f, :is_closed %>


  <%= submit "ذخیره", phx_disable_with: "در حال ذخیره سازی ..." %>
</form>
</div>

lib/mafia_web/live/session_live/index.html.leex
<div class="admin">
  <h1>لیست مسابقات</h1>

  <%= if @live_action in [:new, :edit] do %>
    <%= live_modal @socket, MafiaWeb.SessionLive.FormComponent,
      id: @session.id || :new,
      title: @page_title,
      action: @live_action,
      session: @session,
      return_to: Routes.session_index_path(@socket, :index) %>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>عنوان</th>
        <th>توضیحات</th>
        <th>انتشار یافته</th>
        <th>بسته شده</th>
        <th>تعداد کل شرکت کننده ها</th>

        <th></th>
      </tr>
    </thead>
    <tbody id="session">
      <%= for session <- @session_collection do %>
        <tr id="session-<%= session.id %>">
          <td><%= session.title %></td>
          <td><%= session.description %></td>
          <td><%= if session.is_published do %>بله <% else %> خیر <% end %></td>
          <td><%= if session.is_closed do %>بله <% else %> خیر <% end %></td>
          <td><%= session.total_vote_count %></td>

          <td>
            <%= live_redirect to: Routes.question_index_path(@socket, :index, session.id) do %>
              <span class="list material-icons" title="نمایش سوالات">list</span>
            <% end %>
            <%= live_redirect to: Routes.session_show_path(@socket, :show, session) do %>
              <span class="list material-icons" title="نمایش جزییات">preview</span>
            <% end %>
            <%= live_patch to: Routes.session_index_path(@socket, :edit, session) do %>
              <span class="edit material-icons" title="ویرایش">edit</span>
            <% end %>
            <%= link to: "#", phx_click: "delete", phx_value_id: session.id, data: [confirm: "از حذف گزینه اطمینان دارید؟"]  do %>
              <span class="delete material-icons" title="حذف">delete</span>
            <% end %>
            <%= if @is_playing and @current_game_id == session.id do %>
            <button phx-click="game_page"  phx-value-sessionid=<%= session.id %>>صفحه اجرای مسابقه</button>
            <% end %>
            <%= if @is_playing == false do %>
              <%= if session.is_closed == false do %>
              <button phx-click="start_game" phx-value-sessionid=<%= session.id %>>شروع بازی</button>
              <% end %>
              <button><a href="/super-admin/session/contest/<%= session.id %>">مشاهده نتایج</a></button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= live_patch to: Routes.session_index_path(@socket, :new) do%>
    <div class="add">
      <span class="material-icons">add</span>
      ایجاد مسابقه جدید
    </div>
	<% end %>
</div>

lib/mafia_web/live/session_live/show.html.leex
<div class="admin" id="show-session">
  <h1>Show Session</h1>

  <%= if @live_action in [:edit] do %>
    <%= live_modal @socket, MafiaWeb.SessionLive.FormComponent,
      id: @session.id,
      title: @page_title,
      action: @live_action,
      session: @session,
      return_to: Routes.session_show_path(@socket, :show, @session) %>
  <% end %>

  <ul>

    <li>
      <strong>Title:</strong>
      <%= @session.title %>
    </li>

    <li>
      <strong>Description:</strong>
      <%= @session.description %>
    </li>

    <li>
      <strong>Image path:</strong>
      <%= @session.image_path %>
    </li>

    <li>
      <strong>Video path:</strong>
      <%= @session.video_path %>
    </li>

    <li>
      <strong>Is published:</strong>
      <%= @session.is_published %>
    </li>

    <li>
      <strong>Is closed:</strong>
      <%= @session.is_closed %>
    </li>

    <li>
      <strong>Total vote count:</strong>
      <%= @session.total_vote_count %>
    </li>

  </ul>

  <%= live_patch to: Routes.session_show_path(@socket, :edit, @session) do%>
      <div class="add">
        <span class="material-icons">edit</span>
        ویرایش
      </div>
    <% end %>
    <%= live_redirect to: Routes.session_index_path(@socket, :index) do%>
      <div class="back">
        <span class="material-icons">arrow_back</span>
        بازگشت
      </div>
    <% end %>
</div>